language: go
go: 
 - 1.5.1
 - tip

install:
  - go get github.com/chonthu/ssh
  - go get github.com/fatih/color
  - go get gopkg.in/alecthomas/kingpin.v2
  - go get gopkg.in/yaml.v2

gobuild_args: -x -ldflags "-X main.Version=`git describe --tags --dirty --always`"

script:
 - go test -v ./...